title: Load an image onto the Sense HAT LED matrix
hero_image: images/banner.png
description: Learn how to load a PNG or JPG image onto the Sense HAT LED matrix
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python"
steps:
  - title: Step one
